name: Azure-vm-poc workflow

on:
  push:
    branches:
      - TobeAdd
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest

    env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
        ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
        ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
        ARM_TENANT_ID: ${{ secrets.TENANTID }}
        TF_VAR_vm_username: ${{ secrets.VM_USERNAME }}
        TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}
        TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTIONID }}
        
        
    steps:
    # Step 1: Check out the repository code
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Step 2: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.5


    # Step 4: Initialize Terraform
    - name: Terraform Init
      working-directory: azure-vm-poc
      run: terraform init

    # Step 5: Run Terraform Plan
    - name: Terraform Plan
      working-directory: azure-vm-poc
      run: terraform plan -var-file="terraform.tfvars"

    # Step 6: Apply Terraform Changes (run only on main branch)
    - name: Terraform Apply
      working-directory: azure-vm-poc
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
      if: github.ref == 'refs/heads/main'
