name: Terraform Destroy

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: azure-vm-poc

    env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTIONID }}
          ARM_CLIENT_ID: ${{ secrets.CLIENTID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENTSECRET }}
          ARM_TENANT_ID: ${{ secrets.TENANTID }}
          TF_VAR_vm_username: ${{ secrets.VM_USERNAME }}
          TF_VAR_vm_password: ${{ secrets.VM_PASSWORD }}
          TF_VAR_subscription_id: ${{ secrets.SUBSCRIPTIONID }}

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Initialize Terraform
      - name: Initialize Terraform
        run: terraform init

      # Step 5: Destroy Terraform infrastructure
      - name: Destroy Terraform infrastructure
        run: terraform destroy -auto-approve
